table DimUsers
	lineageTag: 2a9408b3-3af6-44e9-bbd9-b4d052945523

	column UserId
		dataType: int64
		formatString: 0
		lineageTag: 83103a66-2762-4d5a-9dfe-3e8f36e4521c
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column UserName
		dataType: string
		lineageTag: 11f1095d-1aba-4a6f-bde8-d08e867f4141
		summarizeBy: none
		sourceColumn: UserName

		annotation SummarizationSetBy = Automatic

	partition DimUsers = m
		mode: import
		source =
				let
				    Source = stg_CustomUsers,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"AspNetUsers", "Expenses", "Friendships(Id)", "Friendships(Id) 2", "TripParticipants", "Trips"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Id", "UserId"}, {"CustomUserName", "UserName"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

